name: SecretProxy
on:
  repository_dispatch:
    types: [go_fetch]

jobs:
  fetch_site:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch from Render
        run: |
          # גיטהאב פונה לרנדר בסתר. אף אחד לא רואה את זה מהדפדפן שלך.
          curl -L "${{ secrets.RENDER_URL }}?token=23603892&url=${{ github.event.client_payload.url }}" > result.html
      
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
